name: Persona CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Menggunakan Node.js versi ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
# Tidak perlu run server di continuous integration
# Jalankan build fe dan test API di be
#      - run: npm start --prefix back-end
      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCES_TOKEN }}
      - name: Konfigurasi Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build dan push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/persona:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/persona:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/persona:buildcache,mode=max